remove old package after new has been built.
This also introduces vlog, enable verbose output with -v switch

Closes #7

diff --git a/aur-repo b/aur-repo
--- a/aur-repo
+++ b/aur-repo
@@ -7,7 +7,7 @@
 #        Based on work by Thorsten Toepper, who initially created aur-repo.
 #        Thorsten's version was inspired and partly based on work by
 #        Stefan Husmann and Michal Krenek
-VERSION=1.0.0
+VERSION="1.1.0dev"
 
 AURURL="http://aur.archlinux.org/packages"
 REBUILD=0
@@ -21,10 +21,15 @@ LOGFILE="" # set in setup
 REPOCONF="${BUILDDIR}/repo.conf"
 DRY_RUN=0
 QUIET=0
+VVERBOSE=0
 
 log() {
     [ ${QUIET} -eq 0 ] && echo $@
     [ ${DRY_RUN} -eq 0 ] && echo "[`date +'%Y-%m-%d %H:%M'`]: $@" >> "${LOGFILE}"
+}
+
+vlog() {
+    [ ${VVERBOSE} -eq 1 ] && echo "[v] $@"
 }
 
 die() {
@@ -41,6 +46,7 @@ expand_path() {
 
 shell_run() {
     if [ ${DRY_RUN} -eq 0 ]; then
+        vlog "$@"
         $@
     else
         echo "DRYRUN: $@"
@@ -55,6 +61,12 @@ reporemove() {
 
 repoadd() {
     shell_run repo-add "${PACKAGEDIR}/${REPONAME}${DBEXT}" "${1}"
+}
+
+remove_bin_package() {
+    local package="${1}"
+    reporemove "${package}"
+    shell_run find "${PACKAGEDIR}" -type f -name "${package}-*${PKGEXT}" -delete
 }
 
 download() {
@@ -132,9 +144,6 @@ build() {
     fi
 
     if [ ${REBUILD} -eq 1 ]; then
-        reporemove "${PACKAGE}"
-        shell_run find "${PACKAGEDIR}" -type f -name "${PACKAGE}-*${PKGEXT}" -delete
-
         if [ -d "${BUILDDIR}/${PACKAGE}" ]; then
             cd "${BUILDDIR}/${PACKAGE}"
             shell_run find  . -type f -iname "${PACKAGE}-*${PKGEXT}" -delete
@@ -142,15 +151,18 @@ build() {
             if [ $? -ne 0 ]; then
                 log "(${PACKAGE}) Package build failed...skipping"
                 REBUILD=0
+                return 1
             fi
-            find . -iname "${PACKAGE}-*${PKGEXT}" -exec cp {} "${PACKAGEDIR}/" \;
         else
             log "(${PACKAGE}) Package not found...skipping"
             REBUILD=0
+            return 1
         fi
+        return 0
     fi
 
     cd "${PACKAGEDIR}"
+    return 1
 }
 
 get_data() {
@@ -257,10 +269,13 @@ update_one() {
     fi
 
     REBUILD=1
-    build nodiff
-    get_data
-    if [ $? -eq 0 ]; then
-        repoadd "${PACKAGE}-${PKGVER}-${CARCH}${PKGEXT}"
+    if build nodiff; then
+        remove_bin_package "${PACKAGE}"
+        find "${BUILDDIR}/${PACKAGE}" -iname "${PACKAGE}-*${PKGEXT}" -exec cp {} "${PACKAGEDIR}/" \;
+        get_data
+        if [ $? -eq 0 ]; then
+            repoadd "${PACKAGE}-${PKGVER}-${CARCH}${PKGEXT}"
+        fi
     fi
 
     log "---> update finished."
@@ -285,13 +300,16 @@ update_all() {
                     continue
                 fi
                 REBUILD=1
-                build
-                get_data
-                if [ $? -eq 0 ]; then
-                    shell_run repoadd ${PACKAGE}-${PKGVER}-${CARCH}${PKGEXT}
-                    # clean up build dir (in -git packages)
-                    if [ -d "${BUILDDIR}/${PACKAGE}/src/*-build" ]; then
-                        rm -rf ${BUILDDIR}/${PACKAGE}/src/*-build
+                if build; then
+                    remove_bin_package "${PACKAGE}"
+                    find "${BUILDDIR}/${PACKAGE}" -iname "${PACKAGE}-*${PKGEXT}" -exec cp {} "${PACKAGEDIR}/" \;
+                    get_data
+                    if [ $? -eq 0 ]; then
+                        repoadd ${PACKAGE}-${PKGVER}-${CARCH}${PKGEXT}
+                        # clean up build dir (in -git packages)
+                        if [ -d "${BUILDDIR}/${PACKAGE}/src/*-build" ]; then
+                            rm -rf ${BUILDDIR}/${PACKAGE}/src/*-build
+                        fi
                     fi
                 fi
                 ;;
@@ -299,12 +317,13 @@ update_all() {
                 if ! download; then
                     continue
                 fi
-                build
-                if [ ${REBUILD} -eq 1 ]; then
+                if build; then
+                    remove_bin_package "${PACKAGE}"
+                    find "${BUILDDIR}/${PACKAGE}" -iname "${PACKAGE}-*${PKGEXT}" -exec cp {} "${PACKAGEDIR}/" \;
                     get_data
                     if [ $? -eq 0 ]; then
                         rm -rf ${BUILDDIR}/${PACKAGE}/{src,pkg}
-                        shell_run repoadd ${PACKAGE}-${PKGVER}-${CARCH}${PKGEXT}
+                        repoadd ${PACKAGE}-${PKGVER}-${CARCH}${PKGEXT}
                     fi
                 fi
                 ;;
@@ -415,6 +434,11 @@ fi
 
 if [ "${1}" = "-q" ]; then
     QUIET=1
+    shift
+fi
+
+if [ "${1}" = "-v" -a "${QUIET}" -ne 1 ]; then
+    VVERBOSE=1
     shift
 fi
 
